version: "3.8"
services:
  go_db:
    container_name: go_db
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: steve3571
      MYSQL_DATABASE: docesim_db
      MYSQL_USER: root
      MYSQL_PASSWORD: steve3571
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: {}